CREATE TABLE AUDITORIA_EMPLEADOS (
  ID_AUDITORIA_EMPLEADO INT IDENTITY(1, 1),
  ID_EMPLEADO INT NOT NULL, 
	NOMBRE_APELLIDO VARCHAR(50) NOT NULL,
  HORARIO VARCHAR(50) NOT NULL,
  ID_CARGO INT NOT NULL,
  FECHA DATETIME,
  USUARIOBD VARCHAR(128),
  OPERACION VARCHAR(10),
	CONSTRAINT PK_AUDITORIA_EMPLEADOS PRIMARY KEY(ID_AUDITORIA_EMPLEADO),
	CONSTRAINT FK_ID_CARGO_AUDITORIA_EMPLEADO FOREIGN KEY (ID_CARGO) REFERENCES CARGOS(ID_CARGO)
);

CREATE TRIGGER TRG_AUDITORIA_UPDATE_EMPLEADOS
ON EMPLEADOS FOR UPDATE AS SET NOCOUNT ON
BEGIN
  INSERT INTO AUDITORIA_EMPLEADOS
    SELECT
      DELETED.ID_EMPLEADO,
      DELETED.NOMBRE_APELLIDO,
      DELETED.HORARIO,
      DELETED.ID_CARGO,
      GETDATE() AS FECHA,
      SUSER_SNAME() AS USUARIOBD,
      'UPDATE' AS OPERACION
    FROM DELETED;
END;

CREATE TRIGGER TRG_AUDITORIA_DELETE_EMPLEADOS
ON EMPLEADOS FOR DELETE AS SET NOCOUNT ON
BEGIN
  INSERT INTO AUDITORIA_EMPLEADOS
    SELECT
      DELETED.ID_EMPLEADO,
      DELETED.NOMBRE_APELLIDO,
      DELETED.HORARIO,
      DELETED.ID_CARGO,
      GETDATE() AS FECHA,
      SUSER_SNAME() AS USUARIOBD,
      'DELETE' AS OPERACION
    FROM DELETED;
END;